aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
dataloader:
  num_workers: 3
  pin_memory: true
dataset:
  data_root: ./data_line/
  image_height: 64
  image_max_width: 512
  image_min_width: 32
  name: hw
  train_annotation: train_line_annotation.txt
  valid_annotation: test_line_annotation.txt
device: cuda:0
optimizer:
  max_lr: 0.001
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain:
  cached: /tmp/tranformerorc.pth
  id_or_url: 1nTKlEog9YFK74kPyX0qLwCWi60_YHHk4
  md5: efcabaa6d3adfca8e52bda2fd7d2ee04
quiet: false
seq_modeling: seq2seq
trainer:
  batch_size: 16
  checkpoint: ./checkpoint/transformerocr_checkpoint.pth
  export: ./weights/transformerocr.pth
  iters: 10000
  log: ./train.log
  metrics: 500
  print_every: 100
  valid_every: 1500
transformer:
  decoder_embedded: 256
  decoder_hidden: 256
  dropout: 0.1
  encoder_hidden: 256
  img_channel: 256
vocab: 0123456789.-
weights: https://drive.google.com/uc?id=1nTKlEog9YFK74kPyX0qLwCWi60_YHHk4
